MusicShop/Models/Guitar.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MusicShop.Models
{
    public class Guitar
    {
        public int ID { get; set; }

        [Required]
        public string Name { get; set; }

        public string Image { get; set; }
        
        [Required]
        public int Stock { get; set; }

        [Required]
        public decimal Price { get; set; }

        [Required]
        public string ItemType { get; set; }

        [Required]
        public string Brand { get; set; }
    }
}

MusicShop/Controllers/GuitarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MusicShop.Models;
using System.IO;

namespace MusicShop.Controllers
{
    public class GuitarController : Controller
    {
        DAO dao = new DAO();

        


        // GET: Guitar
        public ActionResult Index()
        {
            List<Guitar> list = dao.ShowAllGuitars();
            return View(list);
        }

        public ActionResult Amps()
        {
            List<Guitar> list = dao.ShowAllGuitars();
            return View(list);
        }

        public ActionResult Search(string search)
        {
            List<Guitar> list = dao.ShowFilterList(search);
            return View(list);
        }

        [HttpGet]
        public ActionResult Add()
        {
           
            return View();
        }

        [HttpGet]
        public ActionResult Single(int id)
        {
            Guitar guitar = dao.ShowOneGuitar(id);
            return View(guitar);
        }

        [HttpPost]
        public ActionResult Add(Guitar guitar)
        {
            

            int counter = 0; 
            counter = dao.InsertGuitar(guitar);
            if (counter == 1)
            {
                ViewBag.Message = "Record inserted successfully";
                ModelState.Clear();
            }
            else
            {
                ViewBag.Message = "Error, " + dao.message;
            }

            return View();
        }

        [HttpGet]
        public ActionResult AddImage()
        {

            return View();
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            Guitar guitar = dao.ShowOneGuitar(id);
            return View(guitar);
        }

        [HttpPost]
        public ActionResult Edit(Guitar guitar)
        {
            if (ModelState.IsValid)
            {
                dao.UpdateGuitar(guitar);
                return RedirectToAction("Index");
            }

            return View(guitar);
        }

        [HttpPost]
        public ActionResult Delete(int ID)
        {
            dao.DeleteGuitar(ID);
            return RedirectToAction("Index");
        }
    }
}

MusicShop/Controllers/ImageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;

namespace MusicShop.Controllers
{
    public class ImageController : Controller
    {
        // GET: Image
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(HttpPostedFileBase file)
        {
            if( file.ContentLength > 0)
            {
                string imgName = Path.GetFileName(file.FileName);
                string imgTxt = Path.GetExtension(imgName);
                if(imgTxt == ".jpg" || imgTxt == ".png")
                {
                    string imgPath = Path.Combine(Server.MapPath("~/Content/Images"), imgName);
                    file.SaveAs(imgPath);
                }
            }
            return View();
        }
    }
}

MusicShop/Views/Guitar/Add.cshtml
@model MusicShop.Models.Guitar
@{
    ViewBag.Title = "Add";
}

<h2>Add Item</h2>

<div id="frmSubmitToBackend">
    <h3>Item Details for entry into database</h3>
    @using (Html.BeginForm("Add", "Guitar", FormMethod.Post, new { id = "frmAddItem" }))
    {

        <p>
          
            @Html.LabelFor(g => g.Name)
            @Html.TextBoxFor(g => g.Name, new { id = "txtItemName" })
        </p>

        <p>
           
            @Html.LabelFor(g => g.Image)
            @Html.TextBoxFor(g => g.Image, new { id = "txtItemImage", @Value = "~/Content/Images/" })
        </p>

        <p>
           
            @Html.LabelFor(g => g.Price)
            @Html.TextBoxFor(g => g.Price, new { id = "txtItemPrice", type = "number", step = "0.01" })
        </p>
        <p>
           
            @Html.LabelFor(g => g.Stock)
            @Html.TextBoxFor(g => g.Stock, new { id = "txtItemStock", type = "number" })
        </p>

        <p>
          
            @Html.LabelFor(g => g.ItemType)
            Guitar: @Html.RadioButton("ItemType", "Guitar")
            Amp: @Html.RadioButton("ItemType", "Amp")
        </p>

        <p>

            @Html.LabelFor(g => g.Brand)
            Fender: @Html.RadioButton("Brand", "Fender")
            Gibson: @Html.RadioButton("Brand", "Gibson")
            Squire: @Html.RadioButton("Brand", "Squire")<br />
            Roland: @Html.RadioButton("Brand", "Roland")
            Marshall: @Html.RadioButton("Brand", "Marshall")
            Vox: @Html.RadioButton("Brand", "Vox")
        </p>

        <p>
            <input id="Submit1" type="submit" value="submit" />
            <input id="Reset1" type="reset" value="reset" />
        </p>
    }
</div>

MusicShop/Views/Guitar/AddImage.cshtml
@{
    ViewBag.Title = "AddImage";
}



<h2>Add and save images</h2>

@using (Html.BeginForm("Index", "Image", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <input type="file" name="file">
    <input type="submit" value="Insert Images">

}

MusicShop/Views/Guitar/Amps.cshtml
@model IEnumerable<MusicShop.Models.Guitar>


@{
    ViewBag.Title = "Amps";
}


@if (Session["userType"] != null && Session["userType"].ToString() == "staff")
{
    <h3>@Html.ActionLink("Add an Image", "AddImage")</h3>
    <h3>@Html.ActionLink("Add a Amp", "Add")</h3>
}
    <h4>
        @using (Html.BeginForm("Search", "Guitar", FormMethod.Get))
        {

        <p>
            Marshall  @Html.RadioButton("search", "Marshall")
            Roland  @Html.RadioButton("search", "Roland")
            Vox  @Html.RadioButton("search", "Vox")
            <input id="Submit1" type="submit" value="submit" />
        </p>
        }
    </h4>



    @foreach (var guitar in Model)
    {
        if (guitar.ItemType == "Amp")
        {
            <div class="singleItemDisp">
                <div class="singleItemDetails">
                    <a href="~/Guitar/Single/@guitar.ID">
                        <img class="listPoster" alt="Item Poster - @guitar.Name"
                             src="@Url.Content(guitar.Image)" />
                        <h2> <span class="itemListTitle">@guitar.Name</span> </h2>

                    </a>

                    <form id="frmAddItemToCart">
                        @Html.Label("lblAmmount" + guitar.ID, "Ammount:")
                        @Html.TextBox("txtAmmount" + guitar.ID, "1", new { @class = "textbox", type = "number" })
                        <input id="add_@guitar.ID" type="button" onclick='addToCart("@guitar.ID")' value="Add to Cart" />
                    </form>
                    <span class="price">€@guitar.Price</span>
                    @if (guitar.Stock > 0)
                    {
                        <span class="haveStock">
                            In Stock
                        </span>
                    }
                    else
                    {
                        <span class="noStock">
                            Out of Stock
                        </span>
                    }
                </div>
                @if (Session["userType"] != null && Session["userType"].ToString() == "staff")
                {
                    <div class="AdminRights">
                        @using (Html.BeginForm("Delete", "Guitar", new { ID = guitar.ID }))
                        {
                            <input type="submit" value="Delete" onclick="return confirm('Are you sure you want to delete this record?')" />
                        }
                        @using (Html.BeginForm("Edit", "Guitar", new { ID = guitar.ID }, FormMethod.Get))
                        {
                            <input type="submit" value="Edit" />
                        }
                    </div>
                }
            </div>



        }


    }
    <div class="clear"></div>

MusicShop/Views/Guitar/Edit.cshtml
@model MusicShop.Models.Guitar

@{
    ViewBag.Title = "Edit";
}


@if (Session["userType"] != null && Session["userType"].ToString() == "staff")
{
    <h2>Edit</h2>

    if (Model == null)
    {
        <h3>No item exists with those credentials</h3>
    }
    else
    {
        <div id="frmSubmitToBackend">
            <h3> Details to be Edited in Database</h3>
            @using (Html.BeginForm("Edit", "Guitar", FormMethod.Post, new { id = "frmEditItem" }))
            {
              
                @Html.LabelFor(g => g.ID)
                @Html.TextBoxFor(g => g.ID, new { id = "txtId", @readonly = "readonly" })
                <p>
               
                    @Html.LabelFor(g => g.Name)
                    @Html.TextBoxFor(g => g.Name, new { id = "txtName" })
                </p>
                <p>
                    
                    @Html.LabelFor(g => g.Image)
                    @Html.TextBoxFor(g => g.Image, new { id = "txtImage" })
                </p>
                <p>
                
                    @Html.LabelFor(g => g.Price)
                    @Html.TextBoxFor(g => g.Price, new { id = "txtPrice", type = "number", step = "0.01" })
                </p>
                <p>
                    <!--Stock-->
                    @Html.LabelFor(g => g.Stock)
                    @Html.TextBoxFor(g => g.Stock, new { id = "txtStock", type = "number" })
                </p>

                <p>
                
                    @Html.LabelFor(m => m.ItemType)
                    Guitar: @Html.RadioButton("ItemType", "Guitar")
                    Amp: @Html.RadioButton("ItemType", "Amp")
                </p>

                <p>
                  
                    @Html.LabelFor(m => m.Brand)
                    Fender: @Html.RadioButton("Brand", "Fender")
                    Gibson: @Html.RadioButton("Brand", "Gibson")
                    Squire: @Html.RadioButton("Brand", "Squire")
                </p>

                <p>
                    <input id="Submit1" type="submit" value="submit" onclick="return confirm('Are you sure you want to edit this record?')" />
                    <input id="Reset1" type="reset" value="reset" />
                </p>
            }
        </div>
    }
}
else
{
    <h2>You do not have access to this page</h2>
}

MusicShop/Views/Guitar/Index.cshtml
@model IEnumerable<MusicShop.Models.Guitar>



@{
    ViewBag.Title = "Index";
}

@if (Session["userType"] != null && Session["userType"].ToString() == "staff")
{

    <h3>@Html.ActionLink("Add an Image", "AddImage")</h3>
    <h3>@Html.ActionLink("Add a Guitar", "Add")</h3>
}

    <h4>
        @using (Html.BeginForm("Search", "Guitar", FormMethod.Get))
        {

        <p>
            Fender  @Html.RadioButton("search", "Fender")
            Gibson  @Html.RadioButton("search", "Gibson")
            Squire  @Html.RadioButton("search", "Squire")
            <input id="Submit1" type="submit" value="submit" />
        </p>
        }
    </h4>

    @foreach (var guitar in Model)
    {
        if (guitar.ItemType == "Guitar")
        {
            <div class="singleItemDisp">
                <div class="singleItemDetails">
                    <a href="~/Guitar/Single/@guitar.ID">
                        <img class="listPoster" alt="Item Poster - @guitar.Name"
                             src="@Url.Content(guitar.Image)" />
                        <h3> <span class="itemListTitle">@guitar.Name</span> </h3>

                    </a>

                    <form id="frmAddItemToCart">
                        @Html.Label("lblAmmount" + guitar.ID, "Quantity:")
                        @Html.TextBox("txtAmmount" + guitar.ID, "1", new { @class = "textbox", type = "number" })
                        <input id="add_@guitar.ID" type="button" onclick='addToCart("@guitar.ID")' value="Add to Cart" />
                    </form>
                    <span class="price">€@guitar.Price</span>
                    @if (guitar.Stock > 0)
                    {
                        <span class="haveStock">
                            In Stock
                        </span>
                    }
                    else
                    {
                        <span class="noStock">
                            Out of Stock
                        </span>
                    }
                </div>
                @if (Session["userType"] != null && Session["userType"].ToString() == "staff")
                {
                    <div class="AdminRights">
                        @using (Html.BeginForm("Delete", "Guitar", new { ID = guitar.ID }))
                        {
                            <input type="submit" value="Delete" onclick="return confirm('Are you sure you want to delete this record?')" />
                        }
                        @using (Html.BeginForm("Edit", "Guitar", new { ID = guitar.ID }, FormMethod.Get))
                        {
                            <input type="submit" value="Edit" />
                        }
                    </div>
                }
            </div>

        }

    }
    <div class="clear"></div>

MusicShop/Views/Guitar/Search.cshtml
@model IEnumerable<MusicShop.Models.Guitar>



@{
    ViewBag.Title = "Search";
}

@if (Session["userType"] != null && Session["userType"].ToString() == "staff")
{
    <h3>@Html.ActionLink("Add an Image", "AddImage")</h3>
    <h3>@Html.ActionLink("Add a Guitar", "Add")</h3>
}

    

    @foreach (var guitar in Model)
    {
        <div class="singleItemDisp">
            <div class="singleItemDetails">
                <a href="~/Guitar/ShowOne/@guitar.ID">
                    <img class="listPoster" alt="Item Poster - @guitar.Name"
                         src="@Url.Content(guitar.Image)" />
                    <h2> <span class="itemListTitle">@guitar.Name</span> </h2>

                </a>

                <form id="frmAddItemToCart">
                    @Html.Label("lblAmmount" + guitar.ID, "Ammount:")
                    @Html.TextBox("txtAmmount" + guitar.ID, "1", new { @class = "textbox", type = "number" })
                    <input id="add_@guitar.ID" type="button" onclick='addToCart("@guitar.ID")' value="Add to Cart" />
                </form>
                <span class="price">€@guitar.Price</span>
                @if (guitar.Stock > 0)
                {
                    <span class="haveStock">
                        In Stock
                    </span>
                }
                else
                {
                    <span class="noStock">
                        Out of Stock
                    </span>
                }
            </div>
            @if (Session["userType"] != null && Session["userType"].ToString() == "staff")
            {
                <div class="AdminRights">
                    @using (Html.BeginForm("Delete", "Guitar", new { ID = guitar.ID }))
                    {
                        <input type="submit" value="Delete" onclick="return confirm('Are you sure you want to delete this record?')" />
                    }
                    @using (Html.BeginForm("Edit", "Guitar", new { ID = guitar.ID }, FormMethod.Get))
                    {
                        <input type="submit" value="Edit" />
                    }
                </div>
            }
        </div>



    }
    <div class="clear"></div>

MusicShop/Views/Guitar/Single.cshtml
@model MusicShop.Models.Guitar
@{
    ViewBag.Title = "Single";
}

<h2>Single</h2>

@if (Model == null)
{
    <h3>No items matching thos credentials</h3>
}

else
{
   
        <div class="singleItemDisp">
            <div class="singleItemDetails">
                <a href="~/Guitar/ShowOne/@Model.ID">
                    <img class="listPoster" alt="Item Poster - @Model.Name"
                         src="@Url.Content(Model.Image)" />
                    <h3> <span class="itemListTitle">@Model.Name</span> </h3>

                </a>

                <form id="frmAddItemToCart">
                    @Html.Label("lblAmmount" + Model.ID, "Quantity:")
                    @Html.TextBox("txtAmmount" + Model.ID, "1", new { @class = "textbox", type = "number" })
                    <input id="add_@Model" type="button" onclick='addToCart("@Model.ID")' value="Add to Cart" />
                </form>
                <span class="price">€@Model.Price</span>
                @if (Model.Stock > 0)
                {
                    <span class="haveStock">
                        In Stock
                    </span>
                }
                else
                {
                    <span class="noStock">
                        Out of Stock
                    </span>
                }
            </div>
            @if (Session["userType"] != null && Session["userType"].ToString() == "staff")
            {
                <div class="AdminRights">
                    @using (Html.BeginForm("Delete", "Guitar", new { ID = Model.ID }))
                    {
                        <input type="submit" value="Delete" onclick="return confirm('Are you sure you want to delete this record?')" />
                    }
                    @using (Html.BeginForm("Edit", "Guitar", new { ID = Model.ID }, FormMethod.Get))
                    {
                        <input type="submit" value="Edit" />
                    }
                </div>
            }
        </div>

    }