MusicShop/Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MusicShop.Controllers
{
    public class AboutController : Controller
    {
        // GET: About
        public ActionResult Index()
        {
            return View();
        }
    }
}

MusicShop/Controllers/AdminController.cs
using MusicShop.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;

namespace MusicShop.Controllers
{
    public class AdminController : Controller
    {
        DAO dao = new DAO();

        

        

        // GET: Admin
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Login()
        {
           
            return View();
        }

        [HttpPost]
        public ActionResult Login(Admin admin)
        {
            
            if (ModelState.IsValid)
            {
                Admin staffRecord = dao.SelectOneAdmin(admin.Email);
                if (staffRecord != null)
                {
                    if (admin.Email == staffRecord.Email)
                    {
                        //This will only happen on first time login at which time we want to hash the password
                        if (admin.Password == staffRecord.Password)
                        {
                            staffRecord.Password = Crypto.HashPassword(admin.Password);
                            dao.UpdateAdmin(staffRecord);
                        }

                        if (Crypto.VerifyHashedPassword(staffRecord.Password, admin.Password))
                        {
                            
                            
                                Session.Clear();
                                Session["userType"] = "staff";
                                Session["email"] = admin.Email;
                                return RedirectToAction("Index");
                            
                            
                       
                        }
                     
                    }
                  
                }
              
            }
            else
            {
                ViewBag.Message = "You must enter valid data in the form.";
            }
            return View();
        }

        [HttpGet]
        public ActionResult Logout()
        {
            if (Session["userType"] != null && Session["userType"].ToString() == "staff")
            {
                Session.Clear();
            }
            return RedirectToAction("Login");
        }

        [HttpGet]
        public ActionResult ListOfAdmin()
        {
            List<Admin> listOfAdmin = null;
            
            
                listOfAdmin = dao.SelectAllAdmin();
                return View(listOfAdmin);
            
           
        }

        [HttpGet]
        public ActionResult AddAdmin()
        {
          
            return View();
        }

        [HttpPost]
        public ActionResult AddAdmin(Admin admin)
        {
            
            admin.Password = Crypto.HashPassword(admin.Password);
            if (dao.InsertAdmin(admin) == 1)
            {
                ViewBag.Message = "Staff member successfully added.";
                return View();
            }
            else
            {
                ViewBag.Message = "Something went wrong... Staff member not added.";
                return View();
            }
        }

        [HttpGet]
        public ActionResult DeleteAdmin()
        {
           
            return View();
        }

        [HttpPost]
        public ActionResult DeleteAdmin(Admin staff)
        {
            
            dao.DeleteAdminMember(staff.Email);
            return RedirectToAction("ListOfAdmin");
        }

        [HttpGet]
        public ActionResult EditPassword()
        {
            
            return View();
        }

        [HttpPost]
        public ActionResult EditPassword(FormCollection form)
        {
            Admin aRecord = dao.SelectOneAdmin(Session["email"].ToString());

            if (Crypto.VerifyHashedPassword(aRecord.Password, form["txtCurrPassword"]))
            {
                aRecord.Password = Crypto.HashPassword(form["txtNewPassword1"]);
                dao.UpdateAdmin(aRecord);
                ViewBag.Message = "Password Changed Successfully";
                return View();
            }
            else
            {
                ViewBag.Message = "The password you entered for Current Password does not match the stored password";
                return View();
            }
        }

        [HttpGet]
        public ActionResult ResetPass()
        {
            
            return View();
        }

        [HttpPost]
        public ActionResult ResetPass(Admin admin)
        {
           
            admin.Password = Crypto.HashPassword("admin");
            dao.UpdateAdmin(admin);
            return RedirectToAction("ListOfAdmin");
        }
    }
}

MusicShop/Controllers/GuitarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MusicShop.Models;
using System.IO;

namespace MusicShop.Controllers
{
    public class GuitarController : Controller
    {
        DAO dao = new DAO();

        


        // GET: Guitar
        public ActionResult Index()
        {
            List<Guitar> list = dao.ShowAllGuitars();
            return View(list);
        }

        public ActionResult Amps()
        {
            List<Guitar> list = dao.ShowAllGuitars();
            return View(list);
        }

        public ActionResult Search(string search)
        {
            List<Guitar> list = dao.ShowFilterList(search);
            return View(list);
        }

        [HttpGet]
        public ActionResult Add()
        {
           
            return View();
        }

        [HttpGet]
        public ActionResult Single(int id)
        {
            Guitar guitar = dao.ShowOneGuitar(id);
            return View(guitar);
        }

        [HttpPost]
        public ActionResult Add(Guitar guitar)
        {
            

            int counter = 0; 
            counter = dao.InsertGuitar(guitar);
            if (counter == 1)
            {
                ViewBag.Message = "Record inserted successfully";
                ModelState.Clear();
            }
            else
            {
                ViewBag.Message = "Error, " + dao.message;
            }

            return View();
        }

        [HttpGet]
        public ActionResult AddImage()
        {

            return View();
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            Guitar guitar = dao.ShowOneGuitar(id);
            return View(guitar);
        }

        [HttpPost]
        public ActionResult Edit(Guitar guitar)
        {
            if (ModelState.IsValid)
            {
                dao.UpdateGuitar(guitar);
                return RedirectToAction("Index");
            }

            return View(guitar);
        }

        [HttpPost]
        public ActionResult Delete(int ID)
        {
            dao.DeleteGuitar(ID);
            return RedirectToAction("Index");
        }
    }
}

MusicShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Music Shop App</title>
    <link rel="stylesheet" type="text/css" href="~/Content/Styles.css" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="~/Content/JavaScript.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    
</head>
<body onload="read()">
    @RenderSection("logged", false)
   
    <div class="container">
        <img src="~/Content/Images/guitar.jpg" title="main image" alt="main image picture">
        <div class="centered">@Html.ActionLink("Sign In", "Index", "Customer")</div>
    </div>
    <div class="navbar">
        @Html.ActionLink("Home", "Index", "Home")
        @Html.ActionLink("Guitars", "Index", "Guitar")
        @Html.ActionLink("Amps", "Amps", "Guitar")
        @Html.ActionLink("About Us", "Index", "About")
        @Html.ActionLink("Empty Cart", "Cart", "Order", null, new { id = "cartQty" })
        <div class="topnav-right">
            @Html.ActionLink("Account", "Index", "Customer")
        </div>
    </div>

    <div id="logins">

        @if (Session != null && Session["userType"] != null && Session["userType"].ToString() == "staff")
        {
            <span class="right">
                @Html.ActionLink("Home", "Index", "Admin") -
                @Html.ActionLink("Logout", "Logout", "Admin")
            </span>
        }

        else if (Session != null && Session["userType"] != null && Session["userType"].ToString() == "customer")
        {
            <span class="right">
                @Html.ActionLink("Home", "Index", "Customer") -
                @Html.ActionLink("Logout", "Logout", "Customer")
            </span>


        }

    </div>

    <br />
    <br>

    <div class="wrapper">

        <main>
            @RenderBody()
          
        </main>
    </div>

    <footer>
        <div class="footer">
            <h4> Check out our social media feeds</h4>
            <div class="social-media">
                <a href="https://facebook.com" target="_blank"><img src="~/Content/Images/facebook.png" /> </a>
                <a href="https://twitter.com" target="_blank"><img src="~/Content/Images/twitter.png" /> </a>
                </div>
                <br />

                Contact information: <a href="mailto:musicshop@gmail.com">musicshop@gmail.com</a>
                &copy; @DateTime.Now.Year - Music Shop
            </div>
            <br />

</footer>
</body>
</html>